<?php


namespace Jar\Pugtemplate\Services;

/*
 * This file is part of the Jar/Pugtemplate project.
 */

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;

/**
 *
 * @author Isaac "DaPedro" Hintenjubel <ih@jcdn.de>
 * @package Pugtemplate
 * @subpackage Services
 */

class PugService {

	/**
	 * compiles a pug file
	 * @param string $template 
	 * @param array $values 
	 * @param bool $debug 
	 * @return string 
	 */
	public static function compile(string $template, array $values=[], $debug = false): string {
		try {
			$template = GeneralUtility::getFileAbsFileName($template);			
			if(!file_exists($template)) {
				return '';
			}

			// Fallback for Quick Debugging
			$dump = GeneralUtility::_GP('pugdump');
			if (!empty($dump)) {
				if ($dump == 1 || strpos($template, $dump) !== false) {
					$debug = 1;
				}
			}

			if($debug) {
				DebuggerUtility::var_dump($values, $template, 11);
			}
			
			$pug = new \Pug\Pug(array(
				'pretty' => false,
				'extension' => '.pug',
				'cache' => \TYPO3\CMS\Core\Core\Environment::getVarPath() . '/cache/code/pug/'
			));
			$out = preg_replace('/<!-- (.*)FEDITOR(.*) -->/Uis', '', preg_replace('/<!-- (.*)DO NOT EDIT THIS FILE MAN(.*) -->/Uis', '', preg_replace('/<!-- BEG(.*)-->/Uis', '', $pug->render($template, $values))));
			
		} catch (\Exception $e) {
			\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($e->getMessage(), 'Error while compiling the PUG Template ' . $template);
		}
		
		if($template == $out) {
			return '';
		}

		return $out;
    }
   
    
    /**
     * @return void
     */
    public static function addPugTemplateContentObject() {
    	$GLOBALS['TYPO3_CONF_VARS']['FE']['ContentObjects']['PUGTEMPLATE'] = \Jar\Pugtemplate\ContentObjects\PugContentObject::class;
    }
}
