<?php


namespace Jar\Pugtemplate\Services;

/*
 * This file is part of the Jar/Pugtemplate project.
 */

use TYPO3\CMS\Core\Core\Environment;
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
use TYPO3\CMS\Extbase\Utility\ExtensionUtility;

/**
 *
 * @author Isaac "DaPedro" Hintenjubel <ih@jcdn.de>
 * @package Pugtemplate
 * @subpackage Services
 */

class PugService {
    
    /**
	 * compiles a pug file
	 *
	 * @param \string $template	
	 * @param array $arguments
	 * @throws Exception
	 * @return \string
	 */
	public static function compile($template = NULL, $arguments= array(), $isValue = false, $debug = false) {
		if(empty($template)) {
			return '';
		}
		try {
			if(!$isValue) {
				$template = GeneralUtility::getFileAbsFileName($template);
			}

			#$dump = GeneralUtility::_GP('pugdump');
			if($debug) {
				#if($dump == 1 || strpos($template, $dump) !== false) {
					DebuggerUtility::var_dump($arguments, $template, 11);
				#}
			}
			
			$pug = new \Pug\Pug(array(
				'pretty' => false,
				'extension' => '.pug',
				'cache' => \TYPO3\CMS\Core\Core\Environment::getVarPath() . '/cache/code/pug/'
			));
			$out = preg_replace('/<!-- (.*)FEDITOR(.*) -->/Uis', '', preg_replace('/<!-- (.*)DO NOT EDIT THIS FILE MAN(.*) -->/Uis', '', preg_replace('/<!-- BEG(.*)-->/Uis', '', $pug->render($template, $arguments))));
			//$out = $pug->render($template, $arguments);
		} catch (\Exception $e) {
			\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($e->getMessage(), 'Fehler beim Kompilieren eines Jade-Tenmplates');
		}
		
		if($template == $out) {
			return '';
		}

		return $out;
    }
   
    
    /**
     * @return void
     */
    public static function addPugTemplateContentObject() {
    	$GLOBALS['TYPO3_CONF_VARS']['FE']['ContentObjects']['PUGTEMPLATE'] = \Jar\Pugtemplate\ContentObjects\PugContentObject::class;
    }
}
