<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7a58f08fc4848c8ec13cfc4e06636d49
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '667aeda72477189d0494fecd327c3641' => __DIR__ . '/..' . '/symfony/var-dumper/Resources/functions/dump.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\VarDumper\\' => 28,
            'Symfony\\' => 8,
        ),
        'P' => 
        array (
            'Pug\\' => 4,
            'Phug\\' => 5,
        ),
        'J' => 
        array (
            'JsPhpize\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\VarDumper\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-dumper',
        ),
        'Symfony\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony',
        ),
        'Pug\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Classes/Services',
        ),
        'Phug\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Classes/Services',
            1 => __DIR__ . '/..' . '/phug/phug/src/Phug/Ast',
            2 => __DIR__ . '/..' . '/phug/phug/src/Phug/Compiler',
            3 => __DIR__ . '/..' . '/phug/phug/src/Phug/DependencyInjection',
            4 => __DIR__ . '/..' . '/phug/phug/src/Phug/Event',
            5 => __DIR__ . '/..' . '/phug/phug/src/Phug/Formatter',
            6 => __DIR__ . '/..' . '/phug/phug/src/Phug/Invoker',
            7 => __DIR__ . '/..' . '/phug/phug/src/Phug/Lexer',
            8 => __DIR__ . '/..' . '/phug/phug/src/Phug/Parser',
            9 => __DIR__ . '/..' . '/phug/phug/src/Phug/Reader',
            10 => __DIR__ . '/..' . '/phug/phug/src/Phug/Renderer',
            11 => __DIR__ . '/..' . '/phug/phug/src/Phug/Util',
        ),
        'JsPhpize\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Classes/Services',
        ),
    );

    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/..' . '/js-transformer/js-transformer/src',
        1 => __DIR__ . '/..' . '/pug-php/pug/src',
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Pug\\' => 
            array (
                0 => __DIR__ . '/..' . '/pug-php/pug/src',
            ),
            'Phug\\' => 
            array (
                0 => __DIR__ . '/..' . '/phug/js-transformer-filter/src',
            ),
        ),
        'N' => 
        array (
            'NodejsPhpFallback\\' => 
            array (
                0 => __DIR__ . '/..' . '/nodejs-php-fallback/nodejs-php-fallback/src',
            ),
        ),
        'J' => 
        array (
            'JsPhpize' => 
            array (
                0 => __DIR__ . '/..' . '/js-phpize/js-phpize/src',
                1 => __DIR__ . '/..' . '/js-phpize/js-phpize-phug/src',
            ),
            'Jade\\' => 
            array (
                0 => __DIR__ . '/..' . '/pug-php/pug/src',
            ),
        ),
    );

    public static $fallbackDirsPsr0 = array (
        0 => __DIR__ . '/..' . '/phug/phug/src/Phug/Phug',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7a58f08fc4848c8ec13cfc4e06636d49::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7a58f08fc4848c8ec13cfc4e06636d49::$prefixDirsPsr4;
            $loader->fallbackDirsPsr4 = ComposerStaticInit7a58f08fc4848c8ec13cfc4e06636d49::$fallbackDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit7a58f08fc4848c8ec13cfc4e06636d49::$prefixesPsr0;
            $loader->fallbackDirsPsr0 = ComposerStaticInit7a58f08fc4848c8ec13cfc4e06636d49::$fallbackDirsPsr0;

        }, null, ClassLoader::class);
    }
}
